require 'date'
require 'yaml'
require 'faker'

require_relative './classes/modules/errors'
require_relative './classes/modules/validator'
require_relative './classes/modules/seed_helper'
require_relative './classes/modules/save_load_helper'

require_relative './classes/library'
require_relative './classes/author'
require_relative './classes/book'
require_relative './classes/order'
require_relative './classes/reader'
require_relative './classes/app'
